apiVersion: v1
kind: Service
metadata:
  name: sample-webapp-service
spec:
  selector:
    app: sample-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001
  type: NodePort
